services:
  app:
    build: .
    image: pokeia:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    restart: unless-stopped

  dev:
    build:
      context: .
      target: builder
    image: pokeia-dev:latest
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    volumes:
      - ./:/app:cached
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
